#include "common.hpp"

// per-connection state
struct Conn
{
    int fd = -1; // connfd

    // === server's intention, for event loop ===
    bool want_read = false;  // want to read from connfd
    bool want_write = false; // want to write to connfd
    bool want_close = false; // want to close connfd

    // === buffered input and output ===
    std::vector<uint8_t> incoming; // data to be parsed by server
    std::vector<uint8_t> outgoing; // response generated by server
};

static void fd_set_nb(int fd);
static Conn *handle_accept(int listenfd);
static void handle_read(Conn *conn);
static bool try_one_request(Conn *conn);
static void handle_write(Conn *conn);

int main()
{
    // listenfd
    int fd = socket(AF_INET, SOCK_STREAM, 0); // IPv4 + TCP
    if (fd < 0)
        die("socket()");

    // allow binding to the same `IP:port` after restart
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    struct sockaddr_in addr = {}; // holds IPv4:port as big-endian numbers
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234);     // port
    addr.sin_addr.s_addr = htonl(0); // 0.0.0.0 (to listen on all network interfaces)
    int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
    if (rv)
        die("bind()");

    // set listenfd to non-blocking mode
    fd_set_nb(fd);

    // listen
    rv = listen(fd, SOMAXCONN);
    if (rv)
        die("listen()");

    // map of all client connections, keyed by fd
    std::vector<Conn *> fd2conn;

    // the event loop
    std::vector<struct pollfd> poll_args;
    while (true)
    {
        // prepare arguments for poll()
        poll_args.clear();
        // - put listenfd in the 1st position
        struct pollfd pfd = {fd, POLLIN, 0};
        poll_args.push_back(pfd);
        // - the rest are connfd's
        for (Conn *conn : fd2conn)
        {
            if (!conn)
                continue;
            struct pollfd pfd = {conn->fd, POLLERR, 0};
            if (conn->want_read)
                pfd.events |= POLLIN;
            if (conn->want_write)
                pfd.events |= POLLOUT;
            poll_args.push_back(pfd);
        }

        // wait for readiness (of at least 1 fd)
        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        if (rv < 0)
        {
            if (errno == EINTR)
                continue; // signal interrupt -> not error
            else
                die("poll"); // error
        }

        // === handle ready listenfd ===
        if (poll_args[0].revents)
        {
            // accept new connection
            if (Conn *conn = handle_accept(fd))
            {
                // put new connection in map
                if (fd2conn.size() <= (size_t)conn->fd)
                    fd2conn.resize(conn->fd + 1);
                fd2conn[conn->fd] = conn;
            }
        }

        // handle ready connfd's
        for (size_t i = 1; i < poll_args.size(); i++)
        {
            uint32_t ready = poll_args[i].revents;
            if (ready == 0)
                continue;

            Conn *conn = fd2conn[poll_args[i].fd];
            if (ready & POLLIN)
            {
                assert(conn->want_read);
                handle_read(conn);
            }
            if (ready & POLLOUT)
            {
                assert(conn->want_write);
                handle_write(conn);
            }

            // close connfd on error or server intention
            if ((ready & POLLERR) || conn->want_close)
            {
                close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }

    return 0;
}

/* set a file descriptor to non-blocking mode. */
static void fd_set_nb(int fd)
{
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno)
    {
        die("fcntl error");
        return;
    }

    flags |= O_NONBLOCK;

    errno = 0;
    fcntl(fd, F_SETFL, flags);
    if (errno)
        die("fcntl error");
}

/*
application callback when listenfd is ready:
accept a new connection; return NULL on error.
*/
static Conn *handle_accept(int listenfd)
{
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(
        listenfd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0)
    {
        msg_errno("accept() error");
        return NULL;
    }

    // (client_addr uses big-endian byte order)
    uint32_t ip = client_addr.sin_addr.s_addr;
    printf("new client from %u.%u.%u.%u:%u\n",
           ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
           ntohs(client_addr.sin_port));

    // set the new connfd to non-blocking mode
    fd_set_nb(connfd);

    // create struct Conn
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true;
    return conn;
}

/* application callback when connfd is readable. */
static void handle_read(Conn *conn)
{
    // non-blocking read
    uint8_t buf[64 * 1024]; // 64 KB
    ssize_t rv = read(conn->fd, buf, sizeof(buf));

    if (rv < 0)
    {
        if (errno == EAGAIN) // actually not ready (kernel's TCP buffer is empty)
            return;
        else
        {
            msg_errno("read() error");
            conn->want_close = true;
            return;
        }
    }

    if (rv == 0)
    { // EOF
        if (conn->incoming.size() == 0)
            msg("client closed");
        else
            msg("unexpected EOF");
        conn->want_close = true;
        return;
    }

    // add new data to 'incoming' buffer
    buf_append(conn->incoming, buf, (size_t)rv);

    // parse request(s) and generate response(s)
    while (try_one_request(conn))
        ;
    // why use a loop: to support 'pipelineing'
    // - normally a client sends 1 request, then waits for 1 response;
    //   a pipelined client sends n requests, then waits for n responses.
    // - the server still handles each request in order,
    //   but it can get multiple requests in 1 read,
    //   effectively reducing the number of IOs.
    // - requests pipelining also reduces latency on the client side,
    //   because it can get multiple response in 1 RTT (round trip time).

    // update intention if needed
    if (conn->outgoing.size() > 0) // has a response
    {
        // request-response protocol: alternate between 2 states
        conn->want_read = false;
        conn->want_write = true;

        // try to write response without waiting for the next event loop iteration
        // - socket is likely ready to write unless kernel's TCP send buffer is full
        // - some "bad" cases:
        //   . network congestion.
        //   . client haven't read previous responses (in case of request pipelining).
        handle_write(conn);
    }
    // else: want_read (still) = true
}

/* process 1 request if there's enough data; return true on success. */
static bool try_one_request(Conn *conn)
{
    // protocol: message = 4-byte header + payload
    if (conn->incoming.size() < 4)
        return false; // keep reading

    // payload size
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4); // little-endian
    if (len > K_MAX_MSG)
    {
        msg("too long");
        conn->want_close = true;
        return false;
    }

    // payload
    if (4 + len > conn->incoming.size())
        return false; // keep reading
    const uint8_t *request = &conn->incoming[4];

    // logging
    printf("client says: len:%u data:%.*s%s\n",
           len, (len < 100 ? len : 100), request, (len > 100 ? "..." : ""));

    // generate response (echo) using the same protocol
    buf_append(conn->outgoing, (const uint8_t *)&len, 4); // little-endian
    buf_append(conn->outgoing, request, len);

    // application logic done, remove request message
    buf_consume(conn->incoming, 4 + len);
    // why not just empty 'incoming' buffer:
    // - because there may be more messages (support 'pipelining').

    return true;
}

/* application callback when connfd is writable. */
static void handle_write(Conn *conn)
{
    // non-blocking write
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());

    if (rv < 0)
    {
        if (errno == EAGAIN) // actually not ready (kernel's TCP buffer is full)
            return;
        else
        {
            msg_errno("write() error");
            conn->want_close = true;
            return;
        }
    }

    // remove written data from 'outgoing' buffer
    buf_consume(conn->outgoing, (size_t)rv);

    // update intention if needed
    if (conn->outgoing.size() == 0) // all data written
    {
        // request-response protocol: alternate between 2 states
        conn->want_read = true;
        conn->want_write = false;
    }
    // else: want_write (still) = true
}