#include "common.hpp"
#include "hashtable.hpp"

// per-connection state
struct Conn
{
    int fd = -1; // connfd

    // === server's intention, for event loop ===
    bool want_read = false;  // want to read from connfd
    bool want_write = false; // want to write to connfd
    bool want_close = false; // want to close connfd

    // === buffered input and output ===
    std::vector<uint8_t> incoming; // data to be parsed by server
    std::vector<uint8_t> outgoing; // response generated by server
};

static Conn *handle_accept(int listenfd);
static void handle_read(Conn *conn);
static void handle_write(Conn *conn);
static bool try_one_request(Conn *conn);

int main()
{
    // listenfd
    int fd = socket(AF_INET, SOCK_STREAM, 0); // IPv4 + TCP
    if (fd < 0)
        die("socket()");

    // allow binding to the same `IP:port` after restart
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    struct sockaddr_in addr = {}; // holds IPv4:port as big-endian numbers
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234);     // port
    addr.sin_addr.s_addr = htonl(0); // 0.0.0.0 (to listen on all network interfaces)
    int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
    if (rv)
        die("bind()");

    // set listenfd to non-blocking mode
    fd_set_nb(fd);

    // listen
    rv = listen(fd, SOMAXCONN);
    if (rv)
        die("listen()");

    // map of all client connections, keyed by fd
    std::vector<Conn *> fd2conn;

    // the event loop
    std::vector<struct pollfd> poll_args;
    while (true)
    {
        // prepare arguments for poll()
        poll_args.clear();
        // - put listenfd in the 1st position
        struct pollfd pfd = {fd, POLLIN, 0};
        poll_args.push_back(pfd);
        // - the rest are connfd's
        for (Conn *conn : fd2conn)
        {
            if (!conn)
                continue;
            struct pollfd pfd = {conn->fd, POLLERR, 0};
            if (conn->want_read)
                pfd.events |= POLLIN;
            if (conn->want_write)
                pfd.events |= POLLOUT;
            poll_args.push_back(pfd);
        }

        // wait for readiness (of at least 1 fd)
        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        if (rv < 0)
        {
            if (errno == EINTR)
                continue; // signal interrupt -> not error
            else
                die("poll"); // error
        }

        // === handle ready listenfd ===
        if (poll_args[0].revents)
        {
            // accept new connection
            if (Conn *conn = handle_accept(fd))
            {
                // put new connection in map
                if (fd2conn.size() <= (size_t)conn->fd)
                    fd2conn.resize(conn->fd + 1);
                fd2conn[conn->fd] = conn;
            }
        }

        // handle ready connfd's
        for (size_t i = 1; i < poll_args.size(); i++)
        {
            uint32_t ready = poll_args[i].revents;
            if (ready == 0)
                continue;

            Conn *conn = fd2conn[poll_args[i].fd];
            if (ready & POLLIN)
            {
                assert(conn->want_read);
                handle_read(conn);
            }
            if (ready & POLLOUT)
            {
                assert(conn->want_write);
                handle_write(conn);
            }

            // close connfd on error or server intention
            if ((ready & POLLERR) || conn->want_close)
            {
                close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }

    return 0;
}

/*
application callback when listenfd is ready:
accept a new connection; return NULL on error.
*/
static Conn *handle_accept(int listenfd)
{
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(
        listenfd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0)
    {
        msg_errno("accept() error");
        return NULL;
    }

    // (client_addr uses big-endian byte order)
    uint32_t ip = client_addr.sin_addr.s_addr;
    printf("new client from %u.%u.%u.%u:%u\n",
           ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
           ntohs(client_addr.sin_port));

    // set the new connfd to non-blocking mode
    fd_set_nb(connfd);

    // create struct Conn
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true;
    return conn;
}

/* application callback when connfd is readable. */
static void handle_read(Conn *conn)
{
    // non-blocking read
    uint8_t buf[64 * 1024]; // 64 KB
    ssize_t rv = read(conn->fd, buf, sizeof(buf));

    if (rv < 0)
    {
        if (errno == EAGAIN) // actually not ready (kernel's TCP buffer is empty)
            return;
        else
        {
            msg_errno("read() error");
            conn->want_close = true;
            return;
        }
    }

    if (rv == 0)
    { // EOF
        if (conn->incoming.size() == 0)
            msg("client closed");
        else
            msg("unexpected EOF");
        conn->want_close = true;
        return;
    }

    // add new data to 'incoming' buffer
    buf_append(conn->incoming, buf, (size_t)rv);

    // parse request(s) and generate response(s)
    while (try_one_request(conn))
        ;
    // why use a loop: to support 'pipelineing'
    // - normally a client sends 1 request, then waits for 1 response;
    //   a pipelined client sends n requests, then waits for n responses.
    // - the server still handles each request in order,
    //   but it can get multiple requests in 1 read,
    //   effectively reducing the number of IOs.
    // - requests pipelining also reduces latency on the client side,
    //   because it can get multiple response in 1 RTT (round trip time).

    // update intention if needed
    if (conn->outgoing.size() > 0) // has a response
    {
        // request-response protocol: alternate between 2 states
        conn->want_read = false;
        conn->want_write = true;

        // try to write response without waiting for the next event loop iteration
        // - socket is likely ready to write unless kernel's TCP send buffer is full
        // - some "bad" cases:
        //   . network congestion.
        //   . client haven't read previous responses (in case of request pipelining).
        handle_write(conn);
    }
    // else: want_read (still) = true
}

// response status
enum
{
    RES_OK = 0,
    RES_ERR = 1,
    RES_NX = 2, // key not found
};

struct Response
{
    uint32_t status = RES_OK;
    std::vector<uint8_t> data;
};

static int32_t parse_req(
    const uint8_t *data, size_t size, std::vector<std::string> &out);
static void make_response(const Response &resp, std::vector<uint8_t> &out);
static void exec_cmd(std::vector<std::string> &cmd, Response &resp);

/* process 1 request if there's enough data;
return true on success. */
static bool try_one_request(Conn *conn)
{
    // payload size
    if (conn->incoming.size() < 4)
        return false; // keep reading
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    if (len > K_MAX_MSG)
    {
        msg("too long");
        conn->want_close = true;
        return false;
    }

    // payload
    if (4 + len > conn->incoming.size())
        return false; // keep reading
    const uint8_t *request = &conn->incoming[4];

    // application logic for 1 request
    std::vector<std::string> cmd;
    if (parse_req(request, len, cmd) < 0)
    {
        conn->want_close = true;
        return false; // error
    }
    Response resp;
    exec_cmd(cmd, resp);
    make_response(resp, conn->outgoing);

    // application logic done, remove request message
    buf_consume(conn->incoming, 4 + len);
    // why not just empty 'incoming' buffer:
    // - because there may be more messages (support request 'pipelining').

    return true;
}

static bool read_u32(
    const uint8_t *&cur, const uint8_t *end, uint32_t &out);
static bool read_str(
    const uint8_t *&cur, const uint8_t *end, size_t n, std::string &out);

/* parse request payload (command);
return 0 if success, -1 if fail. */
static int32_t parse_req(
    const uint8_t *data, size_t size, std::vector<std::string> &out)
{
    const uint8_t *end = data + size;

    // number of strings
    uint32_t nstr = 0;
    if (!read_u32(data, end, nstr))
        return -1;
    if (nstr > K_MAX_ARGS)
        return -1;

    while (out.size() < nstr)
    {
        // string length
        uint32_t len = 0;
        if (!read_u32(data, end, len))
            return -1;

        // string
        out.push_back(std::string());
        if (!read_str(data, end, len, out.back()))
            return -1;
    }

    if (data != end) // trailing garbage
        return -1;

    return 0;
}

/* read uint32_t from curr.
- advance curr and return true on success.
- return false on failure.
*/
static bool read_u32(
    const uint8_t *&curr, const uint8_t *end, uint32_t &out)
{
    if (curr + 4 > end)
        return false;
    memcpy(&out, curr, 4);
    curr += 4;
    return true;
}

/* read string of size n from curr.
- advance curr and return true on success.
- return false on failure.
*/
static bool read_str(
    const uint8_t *&curr, const uint8_t *end, size_t n, std::string &out)
{
    if (curr + n > end)
        return false;
    out.assign(curr, curr + n);
    curr += n;
    return true;
}

// global states
static struct
{
    HMap db; // top-level hashtable
} g_data;

// KV pair for top-level hashtable
struct Entry
{
    struct HNode node;
    std::string key;
    std::string val;
};

/* equality comparison for 'struct Entry' */
static bool entry_eq(HNode *lhs, HNode *rhs)
{
    struct Entry *le = container_of(lhs, struct Entry, node);
    struct Entry *re = container_of(rhs, struct Entry, node);
    return le->key == re->key;
}

static void exec_get(std::vector<std::string> &cmd, Response &resp);
static void exec_set(std::vector<std::string> &cmd, Response &resp);
static void exec_del(std::vector<std::string> &cmd, Response &resp);

/* execute a request command and produce response. */
static void exec_cmd(std::vector<std::string> &cmd, Response &resp)
{
    if (cmd.size() == 2 && cmd[0] == "get")
        exec_get(cmd, resp);
    else if (cmd.size() == 3 && cmd[0] == "set")
        exec_set(cmd, resp);
    else if (cmd.size() == 2 && cmd[0] == "del")
        exec_del(cmd, resp);
    else // unrecognized command
        resp.status = RES_ERR;
}

/* get dummy entry for lookup. */
static Entry get_key_entry(std::string &key_str)
{
    Entry key;
    key.key.swap(key_str);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    return key;
}

static void exec_get(std::vector<std::string> &cmd, Response &resp)
{
    // dummy entry for lookup
    Entry key = get_key_entry(cmd[1]);

    // hashtable lookup
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (!node)
    {
        resp.status = RES_NX; // not found
        return;
    }

    // copy value
    const std::string &val = container_of(node, Entry, node)->val;
    assert(val.size() <= K_MAX_MSG);
    resp.data.assign(val.begin(), val.end());
}

static void exec_set(std::vector<std::string> &cmd, Response &resp)
{
    // dummy entry for lookup
    Entry key = get_key_entry(cmd[1]);

    // hashtable lookup
    HNode *node = hm_lookup(&g_data.db, &key.node, &entry_eq);
    if (node)
        // found -> update value
        container_of(node, Entry, node)->val.swap(cmd[2]);
    else
    { // not found -> allocate & insert new KV pair
        Entry *ent = new Entry();
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        ent->val.swap(cmd[2]);
        hm_insert(&g_data.db, &ent->node);
    }
}

static void exec_del(std::vector<std::string> &cmd, Response &resp)
{
    // dummy entry for lookup
    Entry key = get_key_entry(cmd[1]);

    // hashtable delete
    HNode *node = hm_delete(&g_data.db, &key.node, &entry_eq);
    if (node)
        // deallocate the KV pair
        delete container_of(node, Entry, node);
}

/* serialize resp to out buffer. */
static void make_response(const Response &resp, std::vector<uint8_t> &out)
{
    uint32_t resp_len = 4 + (uint32_t)resp.data.size();
    buf_append(out, (const uint8_t *)&resp_len, 4);
    buf_append(out, (const uint8_t *)&resp.status, 4);
    buf_append(out, resp.data.data(), resp.data.size());
}

/* application callback when connfd is writable. */
static void handle_write(Conn *conn)
{
    // non-blocking write
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());

    if (rv < 0)
    {
        if (errno == EAGAIN) // actually not ready (kernel's TCP buffer is full)
            return;
        else
        {
            msg_errno("write() error");
            conn->want_close = true;
            return;
        }
    }

    // remove written data from 'outgoing' buffer
    buf_consume(conn->outgoing, (size_t)rv);

    // update intention if needed
    if (conn->outgoing.size() == 0) // all data written
    {
        // request-response protocol: alternate between 2 states
        conn->want_read = true;
        conn->want_write = false;
    }
    // else: want_write (still) = true
}