// stdlib
#include <assert.h>
#include <string.h>
// system
#include <poll.h>
#include <unistd.h>
#include <sys/socket.h>
#include <netinet/ip.h>

#include "common.hpp"
#include "server_utils.hpp"
#include "hashtable.hpp"
#include "zset.hpp"

// per-connection state
struct Conn
{
    int fd = -1; // connfd

    // === server's intention, for event loop ===
    bool want_read = false;  // want to read from connfd
    bool want_write = false; // want to write to connfd
    bool want_close = false; // want to close connfd

    // === buffered input and output ===
    Buffer incoming; // data to be parsed by server
    Buffer outgoing; // response generated by server
};

static Conn *handle_accept(int listenfd);
static void handle_read(Conn *conn);
static void handle_write(Conn *conn);
static bool try_one_request(Conn *conn);

int main()
{
    // listenfd
    int fd = socket(AF_INET, SOCK_STREAM, 0); // IPv4 + TCP
    if (fd < 0)
        die("socket()");

    // allow binding to the same `IP:port` after restart
    int val = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    struct sockaddr_in addr = {}; // holds IPv4:port as big-endian numbers
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234);     // port
    addr.sin_addr.s_addr = htonl(0); // 0.0.0.0 (to listen on all network interfaces)
    int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
    if (rv)
        die("bind()");

    // set listenfd to non-blocking mode
    fd_set_nb(fd);

    // listen
    rv = listen(fd, SOMAXCONN);
    if (rv)
        die("listen()");

    // map of all client connections, keyed by fd
    std::vector<Conn *> fd2conn;

    // the event loop
    std::vector<struct pollfd> poll_args;
    while (true)
    {
        // prepare arguments for poll()
        poll_args.clear();
        // - put listenfd in the 1st position
        struct pollfd pfd = {fd, POLLIN, 0};
        poll_args.push_back(pfd);
        // - the rest are connfd's
        for (Conn *conn : fd2conn)
        {
            if (!conn)
                continue;
            struct pollfd pfd = {conn->fd, POLLERR, 0};
            if (conn->want_read)
                pfd.events |= POLLIN;
            if (conn->want_write)
                pfd.events |= POLLOUT;
            poll_args.push_back(pfd);
        }

        // wait for readiness (of at least 1 fd)
        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        if (rv < 0)
        {
            if (errno == EINTR)
                continue; // signal interrupt -> not error
            else
                die("poll"); // error
        }

        // === handle ready listenfd ===
        if (poll_args[0].revents)
        {
            // accept new connection
            if (Conn *conn = handle_accept(fd))
            {
                // put new connection in map
                if (fd2conn.size() <= (size_t)conn->fd)
                    fd2conn.resize(conn->fd + 1);
                fd2conn[conn->fd] = conn;
            }
        }

        // handle ready connfd's
        for (size_t i = 1; i < poll_args.size(); i++)
        {
            uint32_t ready = poll_args[i].revents;
            if (ready == 0)
                continue;

            Conn *conn = fd2conn[poll_args[i].fd];
            if (ready & POLLIN)
            {
                assert(conn->want_read);
                handle_read(conn);
            }
            if (ready & POLLOUT)
            {
                assert(conn->want_write);
                handle_write(conn);
            }

            // close connfd on error or server intention
            if ((ready & POLLERR) || conn->want_close)
            {
                close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }

    return 0;
}

/*
application callback when listenfd is ready:
accept a new connection; return NULL on error.
*/
static Conn *handle_accept(int listenfd)
{
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(
        listenfd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0)
    {
        msg_errno("accept() error");
        return NULL;
    }

    // (client_addr uses big-endian byte order)
    uint32_t ip = client_addr.sin_addr.s_addr;
    printf("new client from %u.%u.%u.%u:%u\n",
           ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
           ntohs(client_addr.sin_port));

    // set the new connfd to non-blocking mode
    fd_set_nb(connfd);

    // create struct Conn
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true;
    return conn;
}

/* application callback when connfd is readable. */
static void handle_read(Conn *conn)
{
    // non-blocking read
    uint8_t buf[64 * 1024]; // 64 KB
    ssize_t rv = read(conn->fd, buf, sizeof(buf));

    if (rv < 0)
    {
        if (errno == EAGAIN) // actually not ready (kernel's TCP buffer is empty)
            return;
        else
        {
            msg_errno("read() error");
            conn->want_close = true;
            return;
        }
    }

    if (rv == 0)
    { // EOF
        if (conn->incoming.size() == 0)
            msg("client closed");
        else
            msg("unexpected EOF");
        conn->want_close = true;
        return;
    }

    // add new data to 'incoming' buffer
    buf_append(conn->incoming, buf, (size_t)rv);

    // parse request(s) and generate response(s)
    while (try_one_request(conn))
        ;
    // why use a loop: to support 'pipelineing'
    // - normally a client sends 1 request, then waits for 1 response;
    //   a pipelined client sends n requests, then waits for n responses.
    // - the server still handles each request in order,
    //   but it can get multiple requests in 1 read,
    //   effectively reducing the number of IOs.
    // - requests pipelining also reduces latency on the client side,
    //   because it can get multiple response in 1 RTT (round trip time).

    // update intention if needed
    if (conn->outgoing.size() > 0) // has a response
    {
        // request-response protocol: alternate between 2 states
        conn->want_read = false;
        conn->want_write = true;

        // try to write response without waiting for the next event loop iteration
        // - socket is likely ready to write unless kernel's TCP send buffer is full
        // - some "bad" cases:
        //   . network congestion.
        //   . client haven't read previous responses (in case of request pipelining).
        handle_write(conn);
    }
    // else: want_read (still) = true
}

/* application callback when connfd is writable. */
static void handle_write(Conn *conn)
{
    // non-blocking write
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());

    if (rv < 0)
    {
        if (errno == EAGAIN) // actually not ready (kernel's TCP buffer is full)
            return;
        else
        {
            msg_errno("write() error");
            conn->want_close = true;
            return;
        }
    }

    // remove written data from 'outgoing' buffer
    buf_consume(conn->outgoing, (size_t)rv);

    // update intention if needed
    if (conn->outgoing.size() == 0) // all data written
    {
        // request-response protocol: alternate between 2 states
        conn->want_read = true;
        conn->want_write = false;
    }
    // else: want_write (still) = true
}

static int32_t parse_req(
    const uint8_t *data, size_t size, std::vector<std::string> &out);
static void exec_cmd(std::vector<std::string> &cmd, Buffer &out);
static void response_begin(Buffer &out, size_t *header_pos);
static void response_end(Buffer &out, size_t header_pos);

/* process 1 request if there's enough data;
   return true on success. */
static bool try_one_request(Conn *conn)
{
    // payload size
    if (conn->incoming.size() < 4)
        return false; // keep reading
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    if (len > K_MAX_MSG)
    {
        msg("too long");
        conn->want_close = true;
        return false;
    }

    // payload
    if (4 + len > conn->incoming.size())
        return false; // keep reading
    const uint8_t *request = &conn->incoming[4];

    // application logic for 1 request
    std::vector<std::string> cmd;
    if (parse_req(request, len, cmd) < 0)
    {
        msg("bad_request");
        conn->want_close = true;
        return false; // error
    }
    size_t header_pos; // start of response in 'outgoing'
    response_begin(conn->outgoing, &header_pos);
    exec_cmd(cmd, conn->outgoing);
    response_end(conn->outgoing, header_pos);

    // application logic done, remove request message
    buf_consume(conn->incoming, 4 + len);
    // why not just empty 'incoming' buffer:
    // - because there may be more messages (support request 'pipelining').

    return true;
}

/* read uint32_t from curr.
- advance curr and return true on success.
- return false on failure.
*/
static bool read_u32(
    const uint8_t *&curr, const uint8_t *end, uint32_t &out)
{
    if (curr + 4 > end)
        return false;
    memcpy(&out, curr, 4);
    curr += 4;
    return true;
}

/* read string of size n from curr.
- advance curr and return true on success.
- return false on failure.
*/
static bool read_str(
    const uint8_t *&curr, const uint8_t *end, size_t n, std::string &out)
{
    if (curr + n > end)
        return false;
    out.assign(curr, curr + n);
    curr += n;
    return true;
}

/* parse request payload (command);
return 0 if success, -1 if fail. */
static int32_t parse_req(
    const uint8_t *data, size_t size, std::vector<std::string> &out)
{
    const uint8_t *end = data + size;

    // number of strings
    uint32_t nstr = 0;
    if (!read_u32(data, end, nstr))
        return -1;
    if (nstr > K_MAX_ARGS)
        return -1;

    while (out.size() < nstr)
    {
        // string length
        uint32_t len = 0;
        if (!read_u32(data, end, len))
            return -1;

        // string
        out.push_back(std::string());
        if (!read_str(data, end, len, out.back()))
            return -1;
    }

    if (data != end) // trailing garbage
        return -1;

    return 0;
}

// helpers for serialization
static void buf_append_u8(Buffer &buf, uint8_t data)
{
    buf_append(buf, (const uint8_t *)&data, 1);
}
static void buf_append_u32(Buffer &buf, uint32_t data)
{
    buf_append(buf, (const uint8_t *)&data, 4);
}
static void buf_append_i64(Buffer &buf, int64_t data)
{
    buf_append(buf, (const uint8_t *)&data, 8);
}
static void buf_append_dbl(Buffer &buf, double data)
{
    buf_append(buf, (const uint8_t *)&data, 8);
}

// helpers for outputing response to buffer
static void out_nil(Buffer &out)
{
    buf_append_u8(out, TAG_NIL);
}
static void out_str(Buffer &out, const char *s, size_t size)
{
    buf_append_u8(out, TAG_STR);
    buf_append_u32(out, (uint32_t)size);
    buf_append(out, (const uint8_t *)s, size);
}
static void out_int(Buffer &out, int64_t val)
{
    buf_append_u8(out, TAG_INT);
    buf_append_i64(out, val);
}
static void out_dbl(Buffer &out, double val)
{
    buf_append_u8(out, TAG_DBL);
    buf_append_dbl(out, val);
}
static void out_err(
    Buffer &out, uint32_t code, const std::string &msg)
{
    buf_append_u8(out, TAG_ERR);
    buf_append_u32(out, code);
    buf_append_u32(out, (uint32_t)msg.size());
    buf_append(out, (const uint8_t *)msg.data(), msg.size());
}
static void out_arr(Buffer &out, uint32_t n)
{
    buf_append_u8(out, TAG_ARR);
    buf_append_u32(out, n);
    // items are added separately
}
static size_t out_begin_arr(Buffer &out)
{
    buf_append_u8(out, TAG_ARR);
    buf_append_u32(out, 0); // reserve space for size, filled by out_end_arr()
    return out.size() - 4;  // size_pos
}
static void out_end_arr(Buffer &out, size_t size_pos, uint32_t n)
{
    assert(out[size_pos - 1] == TAG_ARR);
    memcpy(&out[size_pos], &n, 4);
}

/* set start of response in out buffer & reserve space for header. */
static void response_begin(Buffer &out, size_t *header_pos)
{
    *header_pos = out.size(); // continue from current end
    buf_append_u32(out, 0);   // reserve space
}

/* final response payload size */
static size_t response_size(Buffer &out, size_t header_pos)
{
    return out.size() - header_pos - 4;
}

/* backfill final response size into response message header;
   error if response is too big. */
static void response_end(Buffer &out, size_t header_pos)
{
    size_t msg_size = response_size(out, header_pos);
    if (msg_size > K_MAX_MSG)
    {
        out.resize(header_pos + 4);
        out_err(out, ERR_TOO_BIG, "response is too big.");
        msg_size = response_size(out, header_pos);
    }

    // message header
    uint32_t len = (uint32_t)msg_size;
    memcpy(&out[header_pos], &len, 4);
}

// global states
static struct
{
    HMap db; // top-level hashtable
} g_data;

// value types
enum ValueType : uint32_t
{
    T_INIT = 0,
    T_STR = 1,  // string
    T_ZSET = 2, // sorted set
};

// KV pair for top-level hashtable
struct Entry
{
    struct HNode node; // intrusive hash table node
    std::string key;

    // === value ===

    uint32_t type = T_INIT;
    std::string str;
    ZSet zset;
};

static Entry *entry_new(uint32_t type)
{
    Entry *ent = new Entry();
    ent->type = type;
    return ent;
}

static void entry_del(Entry *ent)
{
    if (ent->type == T_ZSET)
        zset_clear(&ent->zset);
    delete ent;
}

// dummy Entry without value for lookup
struct LookupKey
{
    struct HNode node; // intrusive hash table node
    std::string key;
};

/* implement HEqFn for 'Entry' and 'LookupKey': compare keys */
static bool entry_eq(HNode *node, HNode *key)
{
    struct Entry *ent = container_of(node, struct Entry, node);
    struct LookupKey *key_data = container_of(key, struct LookupKey, node);
    return ent->key == key_data->key;
}

/* get dummy entry for lookup. */
static LookupKey get_lookup_key(std::string &key_str)
{
    LookupKey key;
    key.key.swap(key_str);
    key.node.hcode = str_hash((uint8_t *)key.key.data(), key.key.size());
    return key;
}

/* get key:
   - get string value by key.
   - response with nil if not found. */
static void exec_get(std::vector<std::string> &cmd, Buffer &out)
{
    // dummy entry for lookup
    LookupKey key = get_lookup_key(cmd[1]);

    // hashtable lookup
    HNode *node = hm_lookup(&g_data.db, &key.node, entry_eq);
    if (!node) // not found
        return out_nil(out);

    // copy value
    Entry *ent = container_of(node, Entry, node);
    if (ent->type != T_STR)
        return out_err(out, ERR_BAD_TYPE, "not a string value");
    return out_str(out, ent->str.data(), ent->str.size());
}

/* set key val:
   - insert key-value pair OR update value by key.
   - response with nil on success. */
static void exec_set(std::vector<std::string> &cmd, Buffer &out)
{
    // dummy entry for lookup
    LookupKey key = get_lookup_key(cmd[1]);

    // hashtable lookup
    HNode *node = hm_lookup(&g_data.db, &key.node, entry_eq);
    if (node)
    { // found -> update value
        Entry *ent = container_of(node, Entry, node);
        if (ent->type != T_STR)
            return out_err(out, ERR_BAD_TYPE, "a non-string value exists");
        ent->str.swap(cmd[2]);
    }
    else
    { // not found -> allocate & insert new KV pair
        Entry *ent = entry_new(T_STR);
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        ent->str.swap(cmd[2]);
        hm_insert(&g_data.db, &ent->node);
    }

    return out_nil(out);
}

/* del key:
   - delete an entry.
   - response: 1 if deleted, 0 if not found. */
static void exec_del(std::vector<std::string> &cmd, Buffer &out)
{
    // dummy entry for lookup
    LookupKey key = get_lookup_key(cmd[1]);

    // hashtable delete
    HNode *node = hm_delete(&g_data.db, &key.node, &entry_eq);
    if (node)
        // deallocate the KV pair
        entry_del(container_of(node, Entry, node));

    return out_int(out, node ? 1 : 0);
}

static bool cb_keys(HNode *node, void *args)
{
    Buffer &out = *(Buffer *)args;
    const std::string &key = container_of(node, Entry, node)->key;
    out_str(out, key.data(), key.size());
    return true;
}

/* keys: get all keys in DB. */
static void exec_keys(std::vector<std::string> &, Buffer &out)
{
    out_arr(out, (uint32_t)hm_size(&g_data.db));
    hm_foreach(&g_data.db, &cb_keys, (void *)&out);
}

/* get Entry by LookupKey */
static Entry *get_entry(LookupKey &key)
{
    HNode *hnode = hm_lookup(&g_data.db, &key.node, entry_eq);
    return hnode ? container_of(hnode, Entry, node) : NULL;
}

/* get Entry by key string */
static Entry *get_entry(std::string &key_str)
{
    LookupKey key = get_lookup_key(key_str);
    return get_entry(key);
}

/* zadd zset score name:
   - add (score, name) to zset OR update score of existing name.
   - response: 1 if added, 0 if updated. */
static void exec_zadd(std::vector<std::string> &cmd, Buffer &out)
{
    double score;
    if (!str2dbl(cmd[2], score))
        return out_err(out, ERR_BAD_ARG, "expect double");

    // get entry
    LookupKey key = get_lookup_key(cmd[1]);
    Entry *ent = get_entry(key);

    if (!ent)
    { // not found -> insert new zset
        ent = entry_new(T_ZSET);
        ent->key.swap(key.key);
        ent->node.hcode = key.node.hcode;
        hm_insert(&g_data.db, &ent->node);
    }
    else
    { // check existing key
        if (ent->type != T_ZSET)
            return out_err(out, ERR_BAD_TYPE, "expect zset");
    }

    // add (score, name) or update score of existing name
    const std::string &name = cmd[3];
    bool added = zset_insert(
        &ent->zset, name.data(), name.size(), score);
    return out_int(out, (int64_t)added);
}

/* zrem zset name:
   - remove name from zset.
   - response: 1 if deleted, 0 if not found. */
static void exec_zrem(std::vector<std::string> &cmd, Buffer &out)
{
    // get the zset
    Entry *ent = get_entry(cmd[1]);
    if (!ent)
        return out_int(out, 0);
    if (ent->type != T_ZSET)
        return out_err(out, ERR_BAD_TYPE, "expect zset");
    ZSet *zset = &ent->zset;

    const std::string &name = cmd[2];
    ZNode *znode = zset_lookup(zset, name.data(), name.size());
    if (znode)
        zset_delete(zset, znode);
    return out_int(out, znode ? 1 : 0);
}

/* zscore zset name:
   - get score by name.
   - response with nil if not found. */
static void exec_zscore(std::vector<std::string> &cmd, Buffer &out)
{
    // get the zset
    Entry *ent = get_entry(cmd[1]);
    if (!ent)
        return out_nil(out);
    if (ent->type != T_ZSET)
        return out_err(out, ERR_BAD_TYPE, "expect zset");
    ZSet *zset = &ent->zset;

    const std::string &name = cmd[2];
    ZNode *znode = zset_lookup(zset, name.data(), name.size());
    return znode ? out_dbl(out, znode->score) : out_nil(out);
}

/* zquery zset score name offset limit:
   - seek to 1st pair >= (score, name)
   - move to the successor/predecessor (offset)
   - iterate forward and output.
     response: array of (name, score) tuples in specified range. */
static void exec_zquery(std::vector<std::string> &cmd, Buffer &out)
{
    // parse args
    double score;
    if (!str2dbl(cmd[2], score))
        return out_err(out, ERR_BAD_ARG, "expect double");

    const std::string &name = cmd[3];

    int64_t offset, limit;
    if (!str2int(cmd[4], offset) || !str2int(cmd[5], limit))
        return out_err(out, ERR_BAD_ARG, "expect int");

    // get the zset
    Entry *ent = get_entry(cmd[1]);
    if (!ent)
        return out_arr(out, 0);
    if (ent->type != T_ZSET)
        return out_err(out, ERR_BAD_TYPE, "expect zset");
    ZSet *zset = &ent->zset;

    if (limit <= 0)
        return out_arr(out, 0);

    // seek to the start key
    ZNode *znode = zset_seek_ge(zset, score, name.data(), name.size());
    znode = znode_offset(znode, offset);

    // iterate and output
    size_t arr_size_pos = out_begin_arr(out);
    int64_t n = 0; // TODO: in uint32 range
    while (znode && n < limit)
    {
        out_str(out, znode->name, znode->len);
        out_dbl(out, znode->score);
        n += 2; // (name, score) are counted as separate items
        znode = znode_offset(znode, 1);
    }
    out_end_arr(out, arr_size_pos, (uint32_t)n);
}

/* execute a request command and produce response. */
static void exec_cmd(std::vector<std::string> &cmd, Buffer &out)
{
    if (cmd.size() == 2 && cmd[0] == "get")
        exec_get(cmd, out);
    else if (cmd.size() == 3 && cmd[0] == "set")
        exec_set(cmd, out);
    else if (cmd.size() == 2 && cmd[0] == "del")
        exec_del(cmd, out);
    else if (cmd.size() == 1 && cmd[0] == "keys")
        exec_keys(cmd, out);
    else if (cmd.size() == 4 && cmd[0] == "zadd")
        exec_zadd(cmd, out);
    else if (cmd.size() == 3 && cmd[0] == "zrem")
        exec_zrem(cmd, out);
    else if (cmd.size() == 3 && cmd[0] == "zscore")
        exec_zscore(cmd, out);
    else if (cmd.size() == 6 && cmd[0] == "zquery")
        exec_zquery(cmd, out);
    else
        out_err(out, ERR_UNKNOWN, "unknown command.");
}
