#pragma once

// stdlib
#include <stdint.h>
// C++
#include <vector>
#include <string>

#include "common.hpp"
#include "list.hpp"
#include "hashtable.hpp"
#include "heap.hpp"
#include "zset.hpp"

// per-connection state
struct Conn
{
    int fd = -1; // connfd

    // === server's intention, for event loop ===

    bool want_read = false;  // want to read from connfd
    bool want_write = false; // want to write to connfd
    bool want_close = false; // want to close connfd

    // === buffered input and output ===

    Buffer incoming; // data to be parsed by server
    Buffer outgoing; // response generated by server

    // === timer ===

    uint64_t last_active_ms = 0;
    DList idle_node; // intrusive doubly-linked-list node
};

// global states
static struct
{
    HMap db;                     // top-level hashtable
    std::vector<Conn *> fd2conn; // map fd -> client connection
    DList idle_list;             // timers for idle connections (in descending idle time)
    Heap ttl_heap;               // timers for TTL (use min heap to retrieve next timeout efficiently)
} g_data;

const uint64_t K_IDLE_TIMEOUT_MS = 10000; // way lower than T32max

// value types
enum ValueType : uint32_t
{
    T_INIT = 0,
    T_STR = 1,  // string
    T_ZSET = 2, // sorted set
};

// KV pair for top-level hashtable
struct Entry
{
    struct HNode node; // intrusive hash table node
    std::string key;

    // === for TTL ===
    size_t heap_idx = -1; // array index of corresponding heap item

    // === value ===

    uint32_t type = T_INIT;
    std::string str;
    ZSet zset;
};

Entry *entry_new(uint32_t type);
void entry_del(Entry *ent);
void entry_set_ttl(Entry *ent, uint64_t ttl_ms);
void entry_remove_ttl(Entry *ent);
